name: Data Node Deployment
trigger:
  branches:
    include:
    - main
  paths:
    include:
    - code/*
    - infra/BigDataPool/*
    - infra/CosmosDb/*
    - infra/DataFactory/*
    - infra/KeyVault/*
    - infra/MariaDb/*
    - infra/MySql/*
    - infra/PostgreSql/*
    - infra/SqlDatabase/*
    - infra/SqlPool/*
    - infra/SqlServer/*
    - infra/Synapse/*
    - .ado/workflows/dataDomainDeployment.yml
variables:
  AZURE_RESOURCE_MANAGER_CONNECTION_NAME: False
  AZURE_SUBSCRIPTION_ID: dlzSub
  AZURE_RESOURCE_GROUP_NAME: dlzName-rg
  AZURE_LOCATION: region
stages:
- stage: Validation
  displayName: Validation of ARM templates
  jobs:
  - job: Validation
    displayName: Validation of ARM templates
    continueOnError: false
    pool:
      vmImage: ubuntu-latest
    steps:
    - checkout: self
      name: checkout_repository
      displayName: Checkout repository
      submodules: true
      lfs: false
      clean: true
      continueOnError: false
      enabled: true
    - task: AzureResourceManagerTemplateDeployment@3
      name: key_vault_001_validation
      displayName: Deploy Key Vault 001 - validation
      enabled: true
      continueOnError: false
      inputs:
        deploymentScope: Resource Group
        azureResourceManagerConnection: $(AZURE_RESOURCE_MANAGER_CONNECTION_NAME)
        subscriptionId: $(AZURE_SUBSCRIPTION_ID)
        action: Create Or Update Resource Group
        resourceGroupName: $(AZURE_RESOURCE_GROUP_NAME)
        location: $(AZURE_LOCATION)
        templateLocation: Linked artifact
        csmFile: $(System.DefaultWorkingDirectory)/infra/KeyVault/deploy.keyVault.json
        csmParametersFile: $(System.DefaultWorkingDirectory)/infra/KeyVault/params.keyVault001.json
        deploymentMode: Validation
    - task: PowerShell@2
      name: generate_password_001
      displayName: Generate Password 001
      enabled: true
      continueOnError: false
      inputs:
        targetType: filePath
        filePath: $(System.DefaultWorkingDirectory)/code/GeneratePassword.ps1
        errorActionPreference: stop
        failOnStderr: false
        ignoreLASTEXITCODE: false
        pwsh: true
    - task: AzureResourceManagerTemplateDeployment@3
      name: sql_server_001_validation
      displayName: Deploy SQL Server 001 - validation
      enabled: true
      continueOnError: false
      inputs:
        deploymentScope: Resource Group
        azureResourceManagerConnection: $(AZURE_RESOURCE_MANAGER_CONNECTION_NAME)
        subscriptionId: $(AZURE_SUBSCRIPTION_ID)
        action: Create Or Update Resource Group
        resourceGroupName: $(AZURE_RESOURCE_GROUP_NAME)
        location: $(AZURE_LOCATION)
        templateLocation: Linked artifact
        csmFile: $(System.DefaultWorkingDirectory)/infra/SqlServer/deploy.sqlServer.json
        csmParametersFile: $(System.DefaultWorkingDirectory)/infra/SqlServer/params.sqlServer001.json
        deploymentMode: Validation
        overrideParameters: |
          -administratorLoginPassword "$(password)"
    - task: AzureResourceManagerTemplateDeployment@3
      name: sql_database_001_validation
      displayName: Deploy SQL Database 001 - validation
      enabled: true
      continueOnError: false
      inputs:
        deploymentScope: Resource Group
        azureResourceManagerConnection: $(AZURE_RESOURCE_MANAGER_CONNECTION_NAME)
        subscriptionId: $(AZURE_SUBSCRIPTION_ID)
        action: Create Or Update Resource Group
        resourceGroupName: $(AZURE_RESOURCE_GROUP_NAME)
        location: $(AZURE_LOCATION)
        templateLocation: Linked artifact
        csmFile: $(System.DefaultWorkingDirectory)/infra/SqlDatabase/deploy.sqlDatabase.json
        csmParametersFile: $(System.DefaultWorkingDirectory)/SqlDatabase/params.sqlDatabase001.json
        deploymentMode: Validation
        overrideParameters: |
          -sqlServerAdministratorLoginPassword "$(password)"
    - task: PowerShell@2
      name: generate_password_002
      displayName: Generate Password 002
      enabled: true
      continueOnError: false
      inputs:
        targetType: filePath
        filePath: $(System.DefaultWorkingDirectory)/code/GeneratePassword.ps1
        errorActionPreference: stop
        failOnStderr: false
        ignoreLASTEXITCODE: false
        pwsh: true
    - task: AzureResourceManagerTemplateDeployment@3
      name: maria_db_001_validation
      displayName: Deploy Maria DB 001 - validation
      enabled: true
      continueOnError: false
      inputs:
        deploymentScope: Resource Group
        azureResourceManagerConnection: $(AZURE_RESOURCE_MANAGER_CONNECTION_NAME)
        subscriptionId: $(AZURE_SUBSCRIPTION_ID)
        action: Create Or Update Resource Group
        resourceGroupName: $(AZURE_RESOURCE_GROUP_NAME)
        location: $(AZURE_LOCATION)
        templateLocation: Linked artifact
        csmFile: $(System.DefaultWorkingDirectory)/infra/MariaDb/deploy.mariaDb.json
        csmParametersFile: $(System.DefaultWorkingDirectory)/MariaDb/params.mariaDb001.json
        deploymentMode: Validation
        overrideParameters: |
          -mariaDbServerAdministratorLoginPassword "$(password)"
    - task: PowerShell@2
      name: generate_password_003
      displayName: Generate Password 003
      enabled: true
      continueOnError: false
      inputs:
        targetType: filePath
        filePath: $(System.DefaultWorkingDirectory)/code/GeneratePassword.ps1
        errorActionPreference: stop
        failOnStderr: false
        ignoreLASTEXITCODE: false
        pwsh: true
    - task: AzureResourceManagerTemplateDeployment@3
      name: mysql_db_001_validation
      displayName: Deploy MySQL DB 001 - validation
      enabled: true
      continueOnError: false
      inputs:
        deploymentScope: Resource Group
        azureResourceManagerConnection: $(AZURE_RESOURCE_MANAGER_CONNECTION_NAME)
        subscriptionId: $(AZURE_SUBSCRIPTION_ID)
        action: Create Or Update Resource Group
        resourceGroupName: $(AZURE_RESOURCE_GROUP_NAME)
        location: $(AZURE_LOCATION)
        templateLocation: Linked artifact
        csmFile: $(System.DefaultWorkingDirectory)/infra/MySql/deploy.mySql.json
        csmParametersFile: $(System.DefaultWorkingDirectory)/MySql/params.mySql001.json
        deploymentMode: Validation
        overrideParameters: |
          -mySqlServerAdministratorLoginPassword "$(password)"
    - task: PowerShell@2
      name: generate_password_004
      displayName: Generate Password 004
      enabled: true
      continueOnError: false
      inputs:
        targetType: filePath
        filePath: $(System.DefaultWorkingDirectory)/code/GeneratePassword.ps1
        errorActionPreference: stop
        failOnStderr: false
        ignoreLASTEXITCODE: false
        pwsh: true
    - task: AzureResourceManagerTemplateDeployment@3
      name: postgresql_db_001_validation
      displayName: Deploy PostgreSQL DB 001 - validation
      enabled: true
      continueOnError: false
      inputs:
        deploymentScope: Resource Group
        azureResourceManagerConnection: $(AZURE_RESOURCE_MANAGER_CONNECTION_NAME)
        subscriptionId: $(AZURE_SUBSCRIPTION_ID)
        action: Create Or Update Resource Group
        resourceGroupName: $(AZURE_RESOURCE_GROUP_NAME)
        location: $(AZURE_LOCATION)
        templateLocation: Linked artifact
        csmFile: $(System.DefaultWorkingDirectory)/infra/PostgreSql/deploy.postgreSql.json
        csmParametersFile: $(System.DefaultWorkingDirectory)/PostgreSql/params.postgreSql001.json
        deploymentMode: Validation
        overrideParameters: |
          -postgreSqlServerAdministratorLoginPassword "$(password)"
    - task: AzureResourceManagerTemplateDeployment@3
      name: cosmos_db_001_validation
      displayName: Deploy Cosmos DB 001 - validation
      enabled: true
      continueOnError: false
      inputs:
        deploymentScope: Resource Group
        azureResourceManagerConnection: $(AZURE_RESOURCE_MANAGER_CONNECTION_NAME)
        subscriptionId: $(AZURE_SUBSCRIPTION_ID)
        action: Create Or Update Resource Group
        resourceGroupName: $(AZURE_RESOURCE_GROUP_NAME)
        location: $(AZURE_LOCATION)
        templateLocation: Linked artifact
        csmFile: $(System.DefaultWorkingDirectory)/infra/CosmosDb/deploy.cosmosDb.json
        csmParametersFile: $(System.DefaultWorkingDirectory)/CosmosDb/params.cosmosDb001.json
        deploymentMode: Validation
    - task: AzureResourceManagerTemplateDeployment@3
      name: data_factory_001_validation
      displayName: Deploy Data Factory 001 - validation
      enabled: true
      continueOnError: false
      inputs:
        deploymentScope: Resource Group
        azureResourceManagerConnection: $(AZURE_RESOURCE_MANAGER_CONNECTION_NAME)
        subscriptionId: $(AZURE_SUBSCRIPTION_ID)
        action: Create Or Update Resource Group
        resourceGroupName: $(AZURE_RESOURCE_GROUP_NAME)
        location: $(AZURE_LOCATION)
        templateLocation: Linked artifact
        csmFile: $(System.DefaultWorkingDirectory)/infra/DataFactory/deploy.dataFactory.json
        csmParametersFile: $(System.DefaultWorkingDirectory)/infra/DataFactory/params.dataFactory001.json
        deploymentMode: Validation
    - task: PowerShell@2
      name: generate_password_005
      displayName: Generate Password 005
      enabled: true
      continueOnError: false
      inputs:
        targetType: filePath
        filePath: $(System.DefaultWorkingDirectory)/code/GeneratePassword.ps1
        errorActionPreference: stop
        failOnStderr: false
        ignoreLASTEXITCODE: false
        pwsh: true
    - task: AzureResourceManagerTemplateDeployment@3
      name: synapse_001_validation
      displayName: Deploy Synapse 001 - validation
      enabled: false
      continueOnError: true
      inputs:
        deploymentScope: Resource Group
        azureResourceManagerConnection: $(AZURE_RESOURCE_MANAGER_CONNECTION_NAME)
        subscriptionId: $(AZURE_SUBSCRIPTION_ID)
        action: Create Or Update Resource Group
        resourceGroupName: $(AZURE_RESOURCE_GROUP_NAME)
        location: $(AZURE_LOCATION)
        templateLocation: Linked artifact
        csmFile: $(System.DefaultWorkingDirectory)/infra/Synapse/deploy.synapse.json
        csmParametersFile: $(System.DefaultWorkingDirectory)/infra/Synapse/params.synapse001.json
        deploymentMode: Validation
        overrideParameters: |
          -synapseSqlAdministratorPassword "$(password)"
    - task: AzureResourceManagerTemplateDeployment@3
      name: sql_pool_001_validation
      displayName: Deploy SQL Pool 001 - validation
      enabled: false
      continueOnError: true
      inputs:
        deploymentScope: Resource Group
        azureResourceManagerConnection: $(AZURE_RESOURCE_MANAGER_CONNECTION_NAME)
        subscriptionId: $(AZURE_SUBSCRIPTION_ID)
        action: Create Or Update Resource Group
        resourceGroupName: $(AZURE_RESOURCE_GROUP_NAME)
        location: $(AZURE_LOCATION)
        templateLocation: Linked artifact
        csmFile: $(System.DefaultWorkingDirectory)/infra/SqlPool/deploy.sqlPool.json
        csmParametersFile: $(System.DefaultWorkingDirectory)/infra/SqlPool/params.sqlPool001.json
        deploymentMode: Validation
    - task: AzureResourceManagerTemplateDeployment@3
      name: big_data_pool_001_validation
      displayName: Deploy Big Data Pool 001 - validation
      enabled: false
      continueOnError: true
      inputs:
        deploymentScope: Resource Group
        azureResourceManagerConnection: $(AZURE_RESOURCE_MANAGER_CONNECTION_NAME)
        subscriptionId: $(AZURE_SUBSCRIPTION_ID)
        action: Create Or Update Resource Group
        resourceGroupName: $(AZURE_RESOURCE_GROUP_NAME)
        location: $(AZURE_LOCATION)
        templateLocation: Linked artifact
        csmFile: $(System.DefaultWorkingDirectory)/infra/BigDataPool/deploy.bigDataPool.json
        csmParametersFile: $(System.DefaultWorkingDirectory)/infra/BigDataPool/params.bigDataPool001.json
        deploymentMode: Validation
- stage: Deployment
  displayName: Deployment of ARM templates
  dependsOn: Validation
  condition: and(succeeded(), in(variables['Build.Reason'], 'IndividualCI', 'BatchedCI'))
  jobs:
  - job: Deployment
    displayName: Deployment of ARM templates
    continueOnError: false
    pool:
      vmImage: ubuntu-latest
    steps:
    - checkout: self
      name: checkout_repository
      displayName: Checkout repository
      submodules: true
      lfs: false
      clean: true
      continueOnError: false
      enabled: true
    - task: AzureResourceManagerTemplateDeployment@3
      name: key_vault_001_deployment
      displayName: Deploy Key Vault 001
      enabled: true
      continueOnError: false
      inputs:
        deploymentScope: Resource Group
        azureResourceManagerConnection: $(AZURE_RESOURCE_MANAGER_CONNECTION_NAME)
        subscriptionId: $(AZURE_SUBSCRIPTION_ID)
        action: Create Or Update Resource Group
        resourceGroupName: $(AZURE_RESOURCE_GROUP_NAME)
        location: $(AZURE_LOCATION)
        templateLocation: Linked artifact
        csmFile: $(System.DefaultWorkingDirectory)/infra/KeyVault/deploy.keyVault.json
        csmParametersFile: $(System.DefaultWorkingDirectory)/infra/KeyVault/params.keyVault001.json
        deploymentMode: Incremental
    - task: PowerShell@2
      name: generate_password_001
      displayName: Generate Password 001
      enabled: true
      continueOnError: false
      inputs:
        targetType: filePath
        filePath: $(System.DefaultWorkingDirectory)/code/GeneratePassword.ps1
        errorActionPreference: stop
        failOnStderr: false
        ignoreLASTEXITCODE: false
        pwsh: true
    - task: AzureResourceManagerTemplateDeployment@3
      name: sql_server_001_deployment
      displayName: Deploy SQL Server 001
      enabled: true
      continueOnError: false
      inputs:
        deploymentScope: Resource Group
        azureResourceManagerConnection: $(AZURE_RESOURCE_MANAGER_CONNECTION_NAME)
        subscriptionId: $(AZURE_SUBSCRIPTION_ID)
        action: Create Or Update Resource Group
        resourceGroupName: $(AZURE_RESOURCE_GROUP_NAME)
        location: $(AZURE_LOCATION)
        templateLocation: Linked artifact
        csmFile: $(System.DefaultWorkingDirectory)/infra/SqlServer/deploy.sqlServer.json
        csmParametersFile: $(System.DefaultWorkingDirectory)/infra/SqlServer/params.sqlServer001.json
        deploymentMode: Incremental
        overrideParameters: |
          -administratorLoginPassword "$(password)"
    - task: AzureResourceManagerTemplateDeployment@3
      name: cosmos_db_001_deployment
      displayName: Deploy Cosmos DB 001
      enabled: true
      continueOnError: false
      inputs:
        deploymentScope: Resource Group
        azureResourceManagerConnection: $(AZURE_RESOURCE_MANAGER_CONNECTION_NAME)
        subscriptionId: $(AZURE_SUBSCRIPTION_ID)
        action: Create Or Update Resource Group
        resourceGroupName: $(AZURE_RESOURCE_GROUP_NAME)
        location: $(AZURE_LOCATION)
        templateLocation: Linked artifact
        csmFile: $(System.DefaultWorkingDirectory)/infra/CosmosDb/deploy.cosmosDb.json
        csmParametersFile: $(System.DefaultWorkingDirectory)/CosmosDb/params.cosmosDb001.json
        deploymentMode: Incremental
    - task: AzureResourceManagerTemplateDeployment@3
      name: data_factory_001_deployment
      displayName: Deploy Data Factory 001
      enabled: true
      continueOnError: false
      inputs:
        deploymentScope: Resource Group
        azureResourceManagerConnection: $(AZURE_RESOURCE_MANAGER_CONNECTION_NAME)
        subscriptionId: $(AZURE_SUBSCRIPTION_ID)
        action: Create Or Update Resource Group
        resourceGroupName: $(AZURE_RESOURCE_GROUP_NAME)
        location: $(AZURE_LOCATION)
        templateLocation: Linked artifact
        csmFile: $(System.DefaultWorkingDirectory)/infra/DataFactory/deploy.dataFactory.json
        csmParametersFile: $(System.DefaultWorkingDirectory)/infra/DataFactory/params.dataFactory001.json
        deploymentMode: Incremental
    - task: PowerShell@2
      name: generate_password_005
      displayName: Generate Password 005
      enabled: true
      continueOnError: false
      inputs:
        targetType: filePath
        filePath: $(System.DefaultWorkingDirectory)/code/GeneratePassword.ps1
        errorActionPreference: stop
        failOnStderr: false
        ignoreLASTEXITCODE: false
        pwsh: true
    - task: AzureResourceManagerTemplateDeployment@3
      name: synapse_001_deployment
      displayName: Deploy Synapse 001
      enabled: false
      continueOnError: true
      inputs:
        deploymentScope: Resource Group
        azureResourceManagerConnection: $(AZURE_RESOURCE_MANAGER_CONNECTION_NAME)
        subscriptionId: $(AZURE_SUBSCRIPTION_ID)
        action: Create Or Update Resource Group
        resourceGroupName: $(AZURE_RESOURCE_GROUP_NAME)
        location: $(AZURE_LOCATION)
        templateLocation: Linked artifact
        csmFile: $(System.DefaultWorkingDirectory)/infra/Synapse/deploy.synapse.json
        csmParametersFile: $(System.DefaultWorkingDirectory)/infra/Synapse/params.synapse001.json
        deploymentMode: Incremental
        overrideParameters: |
          -synapseSqlAdministratorPassword "$(password)"
    - task: AzureResourceManagerTemplateDeployment@3
      name: big_data_pool_001_deployment
      displayName: Deploy Big Data Pool 001
      enabled: false
      continueOnError: true
      inputs:
        deploymentScope: Resource Group
        azureResourceManagerConnection: $(AZURE_RESOURCE_MANAGER_CONNECTION_NAME)
        subscriptionId: $(AZURE_SUBSCRIPTION_ID)
        action: Create Or Update Resource Group
        resourceGroupName: $(AZURE_RESOURCE_GROUP_NAME)
        location: $(AZURE_LOCATION)
        templateLocation: Linked artifact
        csmFile: $(System.DefaultWorkingDirectory)/infra/BigDataPool/deploy.bigDataPool.json
        csmParametersFile: $(System.DefaultWorkingDirectory)/infra/BigDataPool/params.bigDataPool001.json
        deploymentMode: Incremental

