name: Update Parameters

on:
  push:
    branches: [main]
    paths:
      - 'config/**'
      - '.github/workflows/updateParameters.yml'

env:
  MANAGEMENT_SUBSCRIPTION_ID: 'mgmtSub'
  GLOBAL_DNS_RG_NAME: 'dns-rg'
  DATA_LANDING_ZONE_SUBSCRIPTION_ID: 'dlzSub'
  DATA_LANDING_ZONE_NAME: 'dlzName'
  LOCATION: 'region'
  SUBNET_ID: 'subnetResourceId'
  SYNAPSE_STORAGE_ACCOUNT_NAME: 'synapseStorage'
  SYNAPSE_STORAGE_ACCOUNT_FILE_SYSTEM_NAME: 'synapseStorageFileSystem'
  AZURE_RESOURCE_MANAGER_CONNECTION_NAME: 'myConnectionName'

jobs:
  renaming:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Check Out Repository
        id: checkout_repository
        uses: actions/checkout@v2
      
      # Install Required Packages
      - name: Install Required Modules
        id: install_modules
        run: |
          echo "Install Modules"
          pwsh -Command "Set-PSRepository -Name "PSGallery" -InstallationPolicy Trusted"
          pwsh -Command "Install-Module -Name powershell-yaml"

      # Update Parameters
      - name: Update Parameters
        id: update_parameters
        run: |
          echo "Updating Parameters"
          pwsh $GITHUB_WORKSPACE/config/UpdateParameters.ps1 \
            -ConfigurationFilePath 'config/config.json' \
            -ManagementSubscriptionId '${{ env.MANAGEMENT_SUBSCRIPTION_ID }}' \
            -GlobalDnsRgName '${{ env.GLOBAL_DNS_RG_NAME }}' \
            -DataLandingZoneSubscriptionId '${{ env.DATA_LANDING_ZONE_SUBSCRIPTION_ID }}' \
            -DataLandingZoneName '${{ env.DATA_LANDING_ZONE_NAME }}' \
            -Location '${{ env.LOCATION }}' \
            -SubnetId '${{ env.SUBNET_ID }}' \
            -SynapseStorageAccountName '${{ env.SYNAPSE_STORAGE_ACCOUNT_NAME }}' \
            -SynapseStorageAccountFileSystemName '${{ env.SYNAPSE_STORAGE_ACCOUNT_FILE_SYSTEM_NAME }}'

      # Create Artifact
      - uses: actions/upload-artifact@v2
        with:
          name: updated-parameters
          path: ${{ github.workspace }}
